### ISSUE TITLE
Bug - Auto focus on input field not working when using @scania/components/dist/core.js

### ISSUE THREAD

**Issue by shaheer-scania** [scania-digital-design-system/sdds#132]
**Describe the bug**  
_Auto focus on input field not working when using @scania/components/dist/core.js

**To Reproduce**   
_Steps to reproduce the behavior:_  
1. Import @scania/components/dist/core.js'
2. Add an input field in the HTML
`<input type="text" id="username" name="username" autofocus></input>`

**Version of SDDS**  
    "@scania/components": "^1.5.0",
    "@scania/theme-light": "^2.2.0",

**Framework and version**  
 HTML project

**Browser information:**  
 All browser

**Additional information:**  
Please fix it as soon as possible we need to have autofocus on username field in login form.

[AB#782](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/782)

**Comment by mmexvr** [comment]
Reason for the input not working with autofocus directly is because the body is hidden at first load. That makes the autofocus not set. Because it takes a certain loadtime before the body is visible. If the body would have been visible at all time then the autofocus would have worked.


A work around with this that you trigger the autofocus after the body is visible. For example with a setinterval() 

This problem is only with default input field and not sdds-textfield

**Comment by shaheer-scania** [comment]
@mmexvr  Thank you for the workaround and it works great. Great work.
We are using input element as we dont have sdds-textfield component with grey background. So it would be great to get a permanent fix for autofocus to work with input element.

**Comment by nathalielindqvist** [comment]
This issue has been resolved in the latest version of the @scania/tegel package.
