### ISSUE TITLE
Bug - dropdown scrollable bugs when having more then 7 items

### ISSUE THREAD

**Issue by mmexvr** [scania-digital-design-system/sdds#233]
**Describe the bug**  
_A clear and concise description of what the bug is._
When you have a dropdown with 7 or more items, the dropdown will turn scrollable. But when clicking outside or inside the dropdown to close it, the whole list will be shown for a millisecond. 

**To Reproduce**   
_Steps to reproduce the behavior and be very detailed_  
1. Go to storybook
2. Add more than 7 options 
3. Close it 

**Expected behavior**  
_A clear and concise description of what you expected to happen._
Have the same styling when closing it

**Screenshots**  
_If applicable, add screenshots to help explain your problem._

**Version of SDDS or which package**  
 _E.g 1.2.3 or @scania/theme-light v2.3.4_
@scania/components 1.14.0

**System information:**  
_Please complete the following information, don't forget version_
 - Framework: Any
 - Device: Desktop
 - OS: macOS
 - Browser Chrome 

[AB#1158](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1158)

**Comment by mmexvr** [comment]
https://user-images.githubusercontent.com/35451568/141755652-52c7b02e-ea00-4762-889d-eafa9606adf3.mov

**Comment by Johnny-Scania** [comment]
I took a quick look at this one. The issue is in max-height:90rem. When it is not set, but rather we use height: fit-content, then the upper issue is not present. However, that one removes the scrolling option - I think the root cause is how we add/remove the "is-open" class that controls the showing/hiding options dropdown. Synchronization of properties that change on this class addition/removal can be improved.

**Comment by mmexvr** [comment]
After some more investigation, there is an animation rules that is "too slow" in this case, causing it to flicker.
