### ISSUE TITLE
Form inside modal

### ISSUE THREAD

**Issue by sssaff** [scania-digital-design-system/sdds#414]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/components, @scania/theme-light

### Package versions

components 4.4.2, theme-light 4.3.2

### Browser

Edge (Chromium)

### Framework

Plain HTML

### Reproduction steps

Form inside modal does not render

### Code example

<sdds-modal size="md" selector="#create-new-folder">
    <h5 slot="sdds-modal-headline">
        Create folder
    </h5>
    <form asp-action="CreateFolder">
        <div slot="sdds-modal-body">
            <div class="sdds-headline-07">Question</div>
            <div class="sdds-form-textfield sdds-textfield-container">
                <input required name="foldername" autocomplete="off" class="sdds-textfield-input-md" />
            </div>
        </div>
        <button type="submit" slot="sdds-modal-actions" class="sdds-btn sdds-btn-primary sdds-btn-md">
            Create
        </button>
        <button slot="sdds-modal-actions" data-dismiss-modal class="sdds-btn sdds-btn-secondary sdds-btn-md">
            Cancel
        </button>
    </form>
</sdds-modal>

### Screenshots

Add/Copy screenshot here

### Expected behaviour

Component x should be able to...

### Console errors

Add warning/error message

### Contact information

staffan.hedelin@scania.com

**Comment by mJarsater** [comment]
I am currently not able to replicate this issue, please reopen the issue if the bu persists.

**Comment by Staffman78** [comment]
There are more bugs than just this one with the filter dropdown. I'm using the storybook for these step-by-step instructions so you must be able to reproduce them.

Bug 1 - filter
Select Option 1
Delete the text Option 1 and click outside the dropdown
Result => "Placeholder" even though Option 1 is selected.
Select option 1 again. Still the text "Placeholder" is shown

Bug 2 - filter
Select Option 1
Delete the text Option 1 and type 3
Select Option 3
Click outside the dropdown and on the dropdown again.
Result -> No options, only option 3

Bug 3 - filter+multiselect
Select Option 1
Delete the text Option 1 and type 3
Select Option 3
Now Option 1 and 3 is selected = correct
But now no options are shown again except for Option 3

There are lots of these bugs and I cannot list all of them

Another issue (not a bug) the filter+multiselect cannot be used when the app has lots of options. The dropdown gets too long and each row is far too high, even when using "small", plus since the filtering is a little bugged, it's to hard to use this component.

**Comment by mJarsater** [comment]
> There are more bugs than just this one with the filter dropdown. I'm using the storybook for these step-by-step instructions so you must be able to reproduce them.
> 
> Bug 1 - filter Select Option 1 Delete the text Option 1 and click outside the dropdown Result => "Placeholder" even though Option 1 is selected. Select option 1 again. Still the text "Placeholder" is shown
> 
> Bug 2 - filter Select Option 1 Delete the text Option 1 and type 3 Select Option 3 Click outside the dropdown and on the dropdown again. Result -> No options, only option 3
> 
> Bug 3 - filter+multiselect Select Option 1 Delete the text Option 1 and type 3 Select Option 3 Now Option 1 and 3 is selected = correct But now no options are shown again except for Option 3
> 
> There are lots of these bugs and I cannot list all of them
> 
> Another issue (not a bug) the filter+multiselect cannot be used when the app has lots of options. The dropdown gets too long and each row is far too high, even when using "small", plus since the filtering is a little bugged, it's to hard to use this component.

Great! Thanks for pointing this out. Just to be sure, are these issues you are experiencing in SDDS or Tegel (@scania/components or @scania/tegel)? Or in both?

**Comment by Staffman78** [comment]
tegel
